import { EVT } from '../EVT'
import { settings } from './Settings'
import { lang } from '../Language'
import { LangTextKey } from '../langText'

type Category = 'crawl' | 'naming' | 'download' | 'enhance' | 'general'
type CategorySchema = {
  [key in Category]: {
    /** 一级分类的 ID */
    id: Category
    /** 一级分类的名称的 i18n 的 key */
    nameKey: LangTextKey
    // 分类名字只需要保存 key 就行了，不需要获取实际文本，等到需要显示的时候再动态获取即可
    /** 二级分类 */
    level2: {
      /** 二级分类的 ID */
      [key: string]: {
        /** 二级分类的 ID */
        id: string
        /** 二级分类的名称的 i18n 的 key */
        nameKey: LangTextKey
      }
    }
  }
}

/** 每个设置的元数据 */
type OptionMeta = {
  /** 每个设置的编号，它会被用来查找设置所在的卡片，以便对卡片进行操作 */
  no: number
  /** 设置名称的 i18n 的 key */
  nameKey: LangTextKey
  /** 设置名称的实际文本 */
  name: string
  /** 所属的一级分类 */
  categoryLevel1: Category
  /** 所属的二级分类 */
  categoryLevel2: string
  /** 是否置顶 */
  pinned: boolean
  /** 该设置的搜索关键词的 i18n 的 key。可能是空数组，因为有些设置的名字就够用了，没有其他推荐的关键词 */
  searchWordKeys: LangTextKey[]
  /** 该设置的搜索关键词 */
  searchWords: string[]
}

/** 保存所有设置项以及分类的元数据 */
class OptionConfigs {
  constructor() {
    this.bindEvents()
  }

  private bindEvents() {
    // 当置顶的设置发生变化时，更新每个设置项的 pinned 属性
    window.addEventListener(EVT.list.settingChange, (ev: CustomEventInit) => {
      const data = ev.detail.data as any
      if (data.name === 'pinnedOptions') {
        this.setPinnedOptions()
      }
    })

    // 当设置初始化完成时，设置每个属性里的 i18n 文本
    window.addEventListener(
      EVT.list.settingInitialized,
      (ev: CustomEventInit) => {
        this.setOptionText()
      }
    )
  }

  private setPinnedOptions() {
    for (const option of this.options) {
      option.pinned = settings.pinnedOptions.includes(option.no)
    }
  }

  private setOptionText() {
    for (const option of this.options) {
      // 设置名称里含有 span 标签，需要去掉，只保留纯文字
      option.name = lang.transl(option.nameKey).replace(/<\/?.+?>/g, '')
      // 设置搜索词数组
      if (option.searchWordKeys.length > 0) {
        option.searchWords = []
        option.searchWords = option.searchWordKeys.map((key) =>
          lang.transl(key).replace(/<\/?.+?>/g, '')
        )
      }
    }
  }

  /** 所有一级分类和其下的二级分类的 schema 信息 */
  public categorySchema: CategorySchema = {
    crawl: {
      id: 'crawl',
      nameKey: '_抓取',
      level2: {
        // 抓取数量
        crawlNumber: {
          id: 'crawlNumber',
          nameKey: '_占位符',
        },
        // 作品类型
        worksType: {
          id: 'worksType',
          nameKey: '_作品类型',
        },
        // 作品数据
        worksData: {
          id: 'worksData',
          nameKey: '_占位符',
        },
      },
    },
    naming: {
      id: 'naming',
      nameKey: '_命名',
      level2: {},
    },
    download: {
      id: 'download',
      nameKey: '_下载',
      level2: {},
    },
    enhance: {
      id: 'enhance',
      nameKey: '_增强',
      level2: {},
    },
    general: {
      id: 'general',
      nameKey: '_通用',
      level2: {},
    },
  }

  /** 所有设置的元数据 */
  public options: OptionMeta[] = [
    // 抓取
    {
      no: 0,
      nameKey: '_抓取多少作品',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 1,
      nameKey: '_抓取多少页面',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 2,
      nameKey: '_作品类型',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 44,
      nameKey: '_年龄限制',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 81,
      nameKey: '_AI作品',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 96,
      nameKey: '_原创作品',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 6,
      nameKey: '_收藏状态',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_书签'],
      searchWords: [],
    },
    {
      no: 23,
      nameKey: '_图片色彩',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 21,
      nameKey: '_图片数量',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 99,
      nameKey: '_不抓取下载过的作品',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 15,
      nameKey: '_抓取每个用户最新的几个作品',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 5,
      nameKey: '_收藏数量',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 7,
      nameKey: '_图片的宽高',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_分辨率'],
      searchWords: [],
    },
    {
      no: 8,
      nameKey: '_图片的宽高比例',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_纵横比'],
      searchWords: [],
    },
    {
      no: 9,
      nameKey: '_id范围',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 10,
      nameKey: '_投稿时间',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_发布时间'],
      searchWords: [],
    },
    {
      no: 11,
      nameKey: '_必须含有tag',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_标签'],
      searchWords: [],
    },
    {
      no: 12,
      nameKey: '_不能含有tag',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_标签'],
      searchWords: [],
    },
    {
      no: 94,
      nameKey: '_标题必须含有',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 95,
      nameKey: '_标题不能含有',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 75,
      nameKey: '_减慢抓取速度',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 47,
      nameKey: '_多图作品的图片数量上限',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 3,
      nameKey: '_多图作品只抓取前几张图片',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 104,
      nameKey: '_多图作品只抓取后几张图片',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 103,
      nameKey: '_多图作品不抓取前几张图片',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 69,
      nameKey: '_多图作品不抓取后几张图片',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 79,
      nameKey: '_特定用户的多图作品不下载最后几张图片',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 35,
      nameKey: '_用户阻止名单',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_黑名单'],
      searchWords: [],
    },
    {
      no: 39,
      nameKey: '_针对特定用户屏蔽标签',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 74,
      nameKey: '_定时抓取的间隔时间',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 54,
      nameKey: '_自动导出抓取结果',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 85,
      nameKey: '_导出ID列表',
      name: '',
      categoryLevel1: 'crawl',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    // 命名
    {
      no: 13,
      nameKey: '_图像作品的命名规则',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_文件名'],
      searchWords: [],
    },
    {
      no: 106,
      nameKey: '_小说的命名规则',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_文件名'],
      searchWords: [],
    },
    {
      no: 50,
      nameKey: '_在不同的页面类型中使用不同的命名规则',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 64,
      nameKey: '_不创建文件夹',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_文件夹'],
      searchWords: [],
    },
    {
      no: 19,
      nameKey: '_为多图作品添加一层文件夹',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_文件夹'],
      searchWords: [],
    },
    {
      no: 38,
      nameKey: '_为r18作品添加一层文件夹',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_文件夹'],
      searchWords: [],
    },
    {
      no: 43,
      nameKey: '_使用第一个匹配的标签建立文件夹',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_文件夹'],
      searchWords: [],
    },
    {
      no: 107,
      nameKey: '_标签别名',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 80,
      nameKey: '_如果作品含有某些标签则对这个作品使用另一种命名规则',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 98,
      nameKey: '_序号起始值',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 22,
      nameKey: '_第一张图不带序号',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 46,
      nameKey: '_在序号前面填充0',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 29,
      nameKey: '_文件名长度限制',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_路径长度'],
      searchWords: [],
    },
    {
      no: 83,
      nameKey: '_标签分隔符号',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 97,
      nameKey: '_移除文件名里的emoji',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_表情符号'],
      searchWords: [],
    },
    {
      no: 67,
      nameKey: '_移除用户名中的at和后续字符',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 66,
      nameKey: '_自定义用户名',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 31,
      nameKey: '_日期格式',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 91,
      nameKey: '_合并系列小说时的命名规则',
      name: '',
      categoryLevel1: 'naming',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    // 下载
    {
      no: 16,
      nameKey: '_下载线程',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_并发'],
      searchWords: [],
    },
    {
      no: 17,
      nameKey: '_自动开始下载',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 33,
      nameKey: '_下载之后收藏作品',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_书签'],
      searchWords: [],
    },
    {
      no: 101,
      nameKey: '_管理下载记录',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 28,
      nameKey: '_不下载重复文件',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_去重'],
      searchWords: [],
    },
    {
      no: 100,
      nameKey: '_在已下载的作品上显示边框',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 90,
      nameKey: '_下载间隔',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 76,
      nameKey: '_点击收藏按钮时下载作品',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_书签'],
      searchWords: [],
    },
    {
      no: 77,
      nameKey: '_点击点赞按钮时下载作品',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 4,
      nameKey: '_动图保存格式',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 24,
      nameKey: '_同时转换多少个动图',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_并发', '_动图_动态图像'],
      searchWords: [],
    },
    {
      no: 26,
      nameKey: '_小说保存格式',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 73,
      nameKey: '_自动合并系列小说',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_连载'],
      searchWords: [],
    },
    {
      no: 105,
      nameKey: '_合并系列小说时的分割阈值',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_连载'],
      searchWords: [],
    },
    {
      no: 27,
      nameKey: '_在小说里保存元数据',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 70,
      nameKey: '_下载小说的封面图片',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 72,
      nameKey: '_下载小说里的内嵌图片',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_插图'],
      searchWords: [],
    },
    {
      no: 49,
      nameKey: '_保存作品的元数据',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_元信息'],
      searchWords: [],
    },
    {
      no: 89,
      nameKey: '_保存作品的简介',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_介绍'],
      searchWords: [],
    },
    {
      no: 30,
      nameKey: '_图片尺寸',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_分辨率'],
      searchWords: [],
    },
    {
      no: 25,
      nameKey: '_文件体积限制',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_上限'],
      searchWords: [],
    },
    {
      no: 82,
      nameKey: '_文件下载顺序',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_排序'],
      searchWords: [],
    },
    {
      no: 20,
      nameKey: '_把文件保存到用户上次选择的位置',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_路径'],
      searchWords: [],
    },
    {
      no: 52,
      nameKey: '_下载完成后显示通知',
      name: '',
      categoryLevel1: 'download',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_提醒'],
      searchWords: [],
    },
    // 增强
    {
      no: 42,
      nameKey: '_把图片显示为灰色',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 84,
      nameKey: '_高亮关注的用户',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 68,
      nameKey: '_显示更大的缩略图',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 63,
      nameKey: '_替换方形缩略图以显示图片比例',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 55,
      nameKey: '_预览作品',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_预览图片'],
      searchWords: [],
    },
    {
      no: 62,
      nameKey: '_长按右键显示大图',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_原图'],
      searchWords: [],
    },
    {
      no: 102,
      nameKey: '_缩略图上按钮的位置',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 40,
      nameKey: '_在作品缩略图上显示放大按钮',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_放大镜'],
      searchWords: [],
    },
    {
      no: 56,
      nameKey: '_在作品缩略图上显示下载按钮',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 14,
      nameKey: '_复制按钮',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 86,
      nameKey: '_在多图作品页面里显示缩略图列表',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 87,
      nameKey: '_预览作品的详细信息',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 48,
      nameKey: '_在搜索页面添加快捷搜索区域',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_快速搜索'],
      searchWords: [],
    },
    {
      no: 92,
      nameKey: '_过滤搜索页面的作品',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 88,
      nameKey: '_在搜索页面里移除已关注用户的作品',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 18,
      nameKey: '_预览搜索结果',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 34,
      nameKey: '_收藏设置',
      name: '',
      categoryLevel1: 'enhance',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_书签'],
      searchWords: [],
    },
    // 通用

    {
      no: 93,
      nameKey: '_日志区域的默认可见性',
      name: '',
      categoryLevel1: 'general',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 78,
      nameKey: '_导出日志',
      name: '',
      categoryLevel1: 'general',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_保存日志'],
      searchWords: [],
    },
    {
      no: 36,
      nameKey: '_颜色主题',
      name: '',
      categoryLevel1: 'general',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_深色模式'],
      searchWords: [],
    },
    {
      no: 41,
      nameKey: '_背景图片',
      name: '',
      categoryLevel1: 'general',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_壁纸', '_皮肤'],
      searchWords: [],
    },
    {
      no: 45,
      nameKey: '_选项卡切换方式',
      name: '',
      categoryLevel1: 'general',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [],
      searchWords: [],
    },
    {
      no: 53,
      nameKey: '_高亮显示关键字',
      name: '',
      categoryLevel1: 'general',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_关键词'],
      searchWords: [],
    },
    {
      no: 32,
      nameKey: '_Language',
      name: '',
      categoryLevel1: 'general',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: [
        '_语言',
        '_中文_简体和繁体_搜索用',
        '_简体中文_搜索用',
        '_正體中文_搜索用',
        '_英语_搜索用',
        '_日语_搜索用',
        '_韩语_搜索用',
        '_俄语_搜索用',
      ],
      searchWords: [],
    },
    {
      no: 37,
      nameKey: '_管理设置',
      name: '',
      categoryLevel1: 'general',
      categoryLevel2: '',
      pinned: false,
      searchWordKeys: ['_导入设置', '_导出设置', '_重置设置'],
      searchWords: [],
    },
  ]
}

const optionConfigs = new OptionConfigs()
export { optionConfigs }
